# 这个文件名为build.yml，放在.github/workflows文件夹中
# 这个工作流会在每次有新的推送到master分支时触发
name: Build Folia
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 这个工作流定义了一个名为build的任务
jobs:
  build:
    # 这个任务运行在ubuntu-latest环境中
    runs-on: ubuntu-latest

    # 这个任务的步骤如下：
    steps:
      # 第一步：使用actions/checkout@v2动作来拉取Folia的源代码
      - name: Checkout Folia
        uses: actions/checkout@v2
        with:
          repository: PaperMC/Folia # Folia的仓库名
          ref: master # Folia的分支名

      # 第二步：使用actions/setup-java@v2动作来安装Java环境
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # Java的发行版
          java-version: '17' # Java的版本

      # 第三步：运行./gradlew applyPatches命令来应用补丁
      - name: Apply patches
        run: ./gradlew applyPatches
        env:
          GIT_AUTHOR_NAME: CerealAxis
          GIT_AUTHOR_EMAIL: none@example.com
          GIT_COMMITTER_NAME: CerealAxis
          GIT_COMMITTER_EMAIL: none@example.com


      # 第四步：运行./gradlew reobfJar命令来编译Folia
      - name: Build Folia
        run: ./gradlew reobfJar

      # 第五步：使用actions/upload-artifact@v2动作来上传编译好的jar文件
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: folia.jar # jar文件的名字
          path: Paper-Server/build/libs/folia.jar # jar文件的路径

